import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider extends ChangeNotifier {
  Locale _locale = const Locale('en');

  Locale get locale => _locale;
  bool get isTamil => _locale.languageCode == 'ta';

  Future<void> init() async {
    final prefs = await SharedPreferences.getInstance();
    final code = prefs.getString('language_code') ?? 'en';
    _locale = Locale(code);
    notifyListeners();
  }

  Future<void> setLanguage(String code) async {
    _locale = Locale(code);
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('language_code', code);
    notifyListeners();
  }

  String translate(String key) {
    final code = _locale.languageCode;
    if (code == 'ta') {
      return _tamilStrings[key] ?? _englishStrings[key] ?? key;
    } else if (code == 'hi') {
      return _hindiStrings[key] ?? _englishStrings[key] ?? key;
    } else if (code == 'ml') {
      return _malayalamStrings[key] ?? _englishStrings[key] ?? key;
    } else if (code == 'kn') {
      return _kannadaStrings[key] ?? _englishStrings[key] ?? key;
    }
    return _englishStrings[key] ?? key;
  }

  static const Map<String, String> _englishStrings = {
    'app_name': 'Urban Serve',
    'welcome_guest': 'Welcome Guest',
    'hey': 'Hey, ',
    'home': 'Home',
    'search_hint': 'Search services, plumbing, cleaning...',
    'detecting_location': 'Detecting location...',
    'gold_flash_sale': 'FLASH SALE',
    'gold_price_sub': '₹1 for 3 months',
    'renew_gold': 'Renew Gold now',
    'explore': 'Explore',
    'offers': 'OFFERS',
    'saved_addresses': 'Saved Addresses',
    'open_map': 'Open Service Map',
    'notifications': 'Notifications',
    'services_bookings': 'SERVICES & BOOKINGS',
    'account_settings_sec': 'ACCOUNT & SETTINGS',
    
    // Categories
    'cat_all': 'All',
    'cat_cleaning': 'Cleaning',
    'cat_plumbing': 'Plumbing',
    'cat_electrical': 'Electrical',
    'cat_ac_service': 'AC Service',
    'cat_painting': 'Painting',
    'cat_carpentry': 'Carpentry',
    'cat_pest_control': 'Pest Control',

    // Filters
    'filters': 'Filters',
    'near_fast': 'Near & Fast',
    'top_rated': 'Top Rated',
    'price_low': 'Price ↑',
    
    // Booking Form
    'book_service': 'Book Service',
    'service_address': 'Service Address',
    'address_hint': 'Enter your full address',
    'address_required': 'Address is required',
    'preferred_date_time': 'Preferred Date & Time (optional)',
    'tap_to_select': 'Tap to select',
    'notes_optional': 'Notes (optional)',
    'notes_hint': 'Any special instructions...',
    'confirm_booking': 'Confirm Booking',
    'booking_placed': 'Booking placed! Proceeding to payment...',
    'booking_failed': 'Booking failed',
    'selected_pro': 'Selected Professional',

    // Bookings
    'my_bookings': 'My Bookings',
    'guest_mode': 'Guest Mode Active',
    'login_prompt': 'Log in to view your booked appointments and track service history.',
    'login_register': 'Log In / Register',
    'cancel_booking_title': 'Cancel Booking',
    'cancel_booking_confirm': 'Are you sure you want to cancel this booking?',
    'no': 'No',
    'yes_cancel': 'Yes, Cancel',
    'booking_cancelled': 'Booking cancelled',
    'failed_to_cancel': 'Failed to cancel booking',
    'rebook': 'Re-book',
    
    // Booking Status
    'status_pending': 'Pending',
    'status_confirmed': 'Confirmed',
    'status_completed': 'Completed',
    'status_cancelled': 'Cancelled',
    'status_in_progress': 'In Progress',
    'status_pending_badge': 'SEARCHING FOR WORKER',
    'status_assigned_badge': 'WORKER ASSIGNED',
    'status_confirmed_badge': 'WORKER ACCEPTED',
    'status_ontheway_badge': 'WORKER ON THE WAY',
    'status_reached_badge': 'WORKER REACHED',
    'status_otppending_badge': 'OTP VERIFICATION PENDING',
    'status_inprogress_badge': 'WORK STARTED',
    'status_invoiceready_badge': 'INVOICE READY',
    'status_paymentpending_badge': 'PAYMENT PENDING',
    'status_completed_badge': 'BOOKING COMPLETED',
    'status_cancelled_badge': 'CANCELLED',

    // Menu / Profile
    'menu': 'Menu',
    'guest_user': 'Guest User',
    'sign_in_access': 'Sign in to access options',
    'account_settings': 'Account Settings',
    'edit_profile': 'Edit Profile',
    'manage_details': 'Manage your personal details',
    'general': 'General',
    'about_app': 'About App',
    'version_info': 'Version info and details',
    'help_support': 'Help & Support',
    'contact_us': 'Contact us for help',
    'logout': 'Logout',
    'logout_confirm': 'Are you sure you want to logout?',
    'cancel': 'Cancel',
    'language': 'Language / மொழி',
    'select_language': 'Select Language',
    'english': 'English',
    'tamil': 'தமிழ் (Tamil)',
    'hindi': 'हिन्दी (Hindi)',
    'malayalam': 'മലയാളം (Malayalam)',
    'kannada': 'ಕನ್ನಡ (Kannada)',
    
    // Help Centre
    'help_centre': 'Help Centre',
    'faq_title': 'Frequently Asked Questions',
    'contact_support': 'Contact Support',
    'call_us': 'Call Us',
    'email_us': 'Email Us',
    'chat_whatsapp': 'Chat on WhatsApp',
    'faq_1_q': 'How do I book a service?',
    'faq_1_a': 'Select a service from the home screen, choose a subcategory, select a professional (optional), set date and time, enter your address, and pay via Razorpay.',
    'faq_2_q': 'Can I cancel a booking?',
    'faq_2_a': 'Yes, bookings can be cancelled anytime before the service starts. Go to "My Bookings" and tap "Cancel Booking".',
    'faq_3_q': 'How do I pay for services?',
    'faq_3_a': 'You can pay online securely using Razorpay, which supports UPI, Cards, Netbanking, and Wallets.',
    'faq_4_q': 'What is the Gold Membership?',
    'faq_4_a': 'Gold membership gives you access to premium professionals, zero platform fees, and exclusive discounts.',
  };

  static const Map<String, String> _tamilStrings = {
    'app_name': 'அர்பன் சர்வ்',
    'welcome_guest': 'வருக விருந்தினரே',
    'hey': 'வணக்கம், ',
    'home': 'முகப்பு',
    'search_hint': 'சேவைகள், குழாய் வேலைகள், கிளீனிங் தேடவும்...',
    'detecting_location': 'இருப்பிடத்தைக் கண்டறிகிறது...',
    'gold_flash_sale': 'மின்னல் விற்பனை',
    'gold_price_sub': '₹1 க்கு 3 மாதங்கள்',
    'renew_gold': 'கோல்ட் மெம்பர்ஷிப் புதுப்பிக்கவும்',
    'explore': 'கண்டறியுங்கள்',
    'offers': 'சலுகைகள்',
    'saved_addresses': 'சேமிக்கப்பட்ட முகவரிகள்',
    'open_map': 'சேவை வரைபடம்',
    'notifications': 'அறிவிப்புகள்',
    'services_bookings': 'சேவைகள் & முன்பதிவுகள்',
    'account_settings_sec': 'கணக்கு & அமைப்புகள்',
    'cat_all': 'அனைத்தும்',
    'cat_cleaning': 'சுத்தம் செய்தல்',
    'cat_plumbing': 'குழாய் வேலை',
    'cat_electrical': 'மின்சாரம்',
    'cat_ac_service': 'ஏசி சேவை',
    'cat_painting': 'வண்ணம் பூசுதல்',
    'cat_carpentry': 'தச்சு வேலை',
    'cat_pest_control': 'பூச்சி கட்டுப்பாடு',
    'filters': 'வடிகட்டிகள்',
    'near_fast': 'அருகில் & விரைவாக',
    'top_rated': 'சிறந்த மதிப்பீடு',
    'price_low': 'விலை ↑',
    'book_service': 'சேவை முன்பதிவு',
    'service_address': 'சேவை முகவரி',
    'address_hint': 'உங்கள் முழு முகவரியை உள்ளிடவும்',
    'address_required': 'முகவரி தேவை',
    'preferred_date_time': 'விரும்பிய தேதி & நேரம் (விரும்பினால்)',
    'tap_to_select': 'தேர்வு செய்ய தட்டவும்',
    'notes_optional': 'குறிப்புகள் (விரும்பினால்)',
    'notes_hint': 'ஏதேனும் சிறப்பு வழிமுறைகள்...',
    'confirm_booking': 'முன்பதிவை உறுதி செய்',
    'booking_placed': 'முன்பதிவு செய்யப்பட்டது! கட்டணப் பக்கத்திற்குச் செல்கிறது...',
    'booking_failed': 'முன்பதிவு தோல்வியடைந்தது',
    'selected_pro': 'தேர்ந்தெடுக்கப்பட்ட வல்லுநர்',
    'my_bookings': 'எனது முன்பதிவுகள்',
    'guest_mode': 'விருந்தினர் பயன்முறை',
    'login_prompt': 'உங்கள் முன்பதிவுகளைக் காண மற்றும் சேவை வரலாற்றைக் கண்காணிக்க உள்நுழையவும்.',
    'login_register': 'உள்நுழைக / பதிவு செய்க',
    'cancel_booking_title': 'முன்பதிவு ரத்து',
    'cancel_booking_confirm': 'இந்த முன்பதிவை ரத்து செய்ய விரும்புகிறீர்களா?',
    'no': 'இல்லை',
    'yes_cancel': 'ஆம், ரத்து செய்',
    'booking_cancelled': 'முன்பதிவு ரத்து செய்யப்பட்டது',
    'failed_to_cancel': 'ரத்து செய்ய முடியவில்லை',
    'rebook': 'மீண்டும் முன்பதிவு',
    'status_pending': 'நிலுவையில்',
    'status_confirmed': 'உறுதி செய்யப்பட்டது',
    'status_completed': 'முடிந்தது',
    'status_cancelled': 'ரத்து செய்யப்பட்டது',
    'status_in_progress': 'செயலில்',
    'status_pending_badge': 'வேலையாள் தேடப்படுகிறது',
    'status_assigned_badge': 'வேலையாள் ஒதுக்கப்பட்டார்',
    'status_confirmed_badge': 'வேலையாள் ஏற்றுக்கொண்டார்',
    'status_ontheway_badge': 'வேலையாள் வந்துகொண்டிருக்கிறார்',
    'status_reached_badge': 'வேலையாள் வந்துவிட்டார்',
    'status_otppending_badge': 'OTP சரிபார்ப்பு நிலுவையில்',
    'status_inprogress_badge': 'வேலை தொடங்கப்பட்டது',
    'status_invoiceready_badge': 'ரசீது தயாராக உள்ளது',
    'status_paymentpending_badge': 'கட்டணம் நிலுவையில்',
    'status_completed_badge': 'முன்பதிவு முடிந்தது',
    'status_cancelled_badge': 'ரத்து செய்யப்பட்டது',
    'menu': 'பட்டி',
    'guest_user': 'விருந்தினர்',
    'sign_in_access': 'மெனுவை அணுக உள்நுழையவும்',
    'account_settings': 'கணக்கு அமைப்புகள்',
    'edit_profile': 'சுயவிவரம் திருத்து',
    'manage_details': 'உங்கள் தனிப்பட்ட விவரங்களை நிர்வகிக்கவும்',
    'general': 'பொதுவானவை',
    'about_app': 'செயலி பற்றி',
    'version_info': 'பதிப்பு விவரங்கள்',
    'help_support': 'உதவி & ஆதரவு',
    'contact_us': 'உதவிக்கு எங்களை தொடர்பு கொள்ளவும்',
    'logout': 'வெளியேறு',
    'logout_confirm': 'நிச்சயமாக வெளியேற விரும்புகிறீர்களா?',
    'cancel': 'ரத்து செய்',
    'language': 'Language / மொழி',
    'select_language': 'மொழியைத் தேர்ந்தெடுக்கவும்',
    'english': 'English',
    'tamil': 'தமிழ் (Tamil)',
    'hindi': 'हिन्दी (Hindi)',
    'malayalam': 'മലയാളം (Malayalam)',
    'kannada': 'ಕನ್ನಡ (Kannada)',
    'help_centre': 'உதவி மையம்',
    'faq_title': 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
    'contact_support': 'ஆதரவை தொடர்பு கொள்ளவும்',
    'call_us': 'அழைக்க',
    'email_us': 'மின்னஞ்சல் செய்ய',
    'chat_whatsapp': 'வாட்ஸ்அப்பில் பேச',
    'faq_1_q': 'ஒரு சேவையை எவ்வாறு முன்பதிவு செய்வது?',
    'faq_1_a': 'முகப்புத் திரையில் இருந்து ஒரு சேவையைத் தேர்ந்தெடுத்து, துணைப்பிரிவைத் தேர்ந்தெடுத்து, வல்லுநரைத் தேர்வுசெய்து (விரும்பினால்), தேதி மற்றும் நேரத்தை அமைத்து, உங்கள் முகவரியை உள்ளிட்டு, ரேஸர்பே மூலம் பணம் செலுத்துங்கள்.',
    'faq_2_q': 'முன்பதிவை ரத்து செய்ய முடியுமா?',
    'faq_2_a': 'ஆம், சேவை தொடங்கும் முன் எப்போது வேண்டுமானாலும் முன்பதிவை ரத்து செய்யலாம். "எனது முன்பதிவுகள்" சென்று "முன்பதிவை ரத்து செய்" என்பதைத் தட்டவும்.',
    'faq_3_q': 'சேவைகளுக்கு எவ்வாறு பணம் செலுத்துவது?',
    'faq_3_a': 'யுபிஐ, கார்டுகள், நெட்பேங்கிங் மற்றும் வாலெட்டுகளை ஆதரிக்கும் ரேஸர்பே மூலம் ஆன்லைனில் பாதுகாப்பாகப் பணம் செலுத்தலாம்.',
    'faq_4_q': 'கோல்ட் மெம்பர்ஷிப் என்றால் என்ன?',
    'faq_4_a': 'கோல்ட் மெம்பர்ஷிப் உங்களுக்கு பிரீமியம் வல்லுநர்களுக்கான அணுகல், பூஜ்ஜிய பிளாட்பார்ம் கட்டணம் மற்றும் பிரத்யேக தள்ளுபடிகளை வழங்குகிறது.',
  };

  static const Map<String, String> _hindiStrings = {
    'app_name': 'अर्बन सर्व',
    'welcome_guest': 'नमस्ते अतिथि',
    'hey': 'नमस्ते, ',
    'search_hint': 'सेवाएं, प्लंबिंग, सफाई खोजें...',
    'detecting_location': 'स्थान खोजा जा रहा है...',
    'gold_flash_sale': 'फ्लैश सेल',
    'gold_price_sub': '₹1 में 3 महीने',
    'renew_gold': 'गोल्ड मेंबरशिप नवीनीकृत करें',
    'explore': 'एक्सप्लोर करें',
    'offers': 'ऑफ़र',
    'cat_all': 'सभी',
    'cat_cleaning': 'सफाई',
    'cat_plumbing': 'प्लंबिंग',
    'cat_electrical': 'इलेक्ट्रिकल',
    'cat_ac_service': 'एसी सेवा',
    'cat_painting': 'पेंटिंग',
    'cat_carpentry': 'बढ़ईगीरी',
    'cat_pest_control': 'कीट नियंत्रण',
    'filters': 'फ़िल्टर',
    'near_fast': 'पास और तेज़',
    'top_rated': 'टॉप रेटेड',
    'price_low': 'मूल्य ↑',
    'book_service': 'सेवा बुक करें',
    'service_address': 'सेवा का पता',
    'address_hint': 'अपना पूरा पता दर्ज करें',
    'address_required': 'पता आवश्यक है',
    'preferred_date_time': 'पसंदीदा तारीख और समय',
    'tap_to_select': 'चुनने के लिए टैप करें',
    'notes_optional': 'नोट्स (वैकल्पिक)',
    'notes_hint': 'कोई विशेष निर्देश...',
    'confirm_booking': 'बुकिंग की पुष्टि करें',
    'booking_placed': 'बुकिंग हो गई! भुगतान पर जा रहे हैं...',
    'booking_failed': 'बुकिंग विफल रही',
    'selected_pro': 'चयनित पेशेवर',
    'my_bookings': 'मेरी बुकिंग',
    'guest_mode': 'अतिथि मोड सक्रिय',
    'login_prompt': 'अपनी बुकिंग देखने के लिए लॉगिन करें।',
    'login_register': 'लॉग इन / रजिस्टर करें',
    'cancel_booking_title': 'बुकिंग रद्द करें',
    'cancel_booking_confirm': 'क्या आप निश्चित रूप से रद्द करना चाहते हैं?',
    'no': 'नहीं',
    'yes_cancel': 'हां, रद्द करें',
    'booking_cancelled': 'बुकिंग रद्द कर दी गई',
    'failed_to_cancel': 'रद्द करने में विफल',
    'rebook': 'पुनः बुक करें',
    'status_pending': 'लंबित',
    'status_confirmed': 'पुष्टि की गई',
    'status_completed': 'पूरा हुआ',
    'status_cancelled': 'रद्द किया गया',
    'status_in_progress': 'प्रगति पर है',
    'menu': 'मेनू',
    'guest_user': 'अतिथि उपयोगकर्ता',
    'sign_in_access': 'विकल्पों के लिए साइन इन करें',
    'account_settings': 'खाता सेटिंग्स',
    'edit_profile': 'प्रोफ़ाइल संपादित करें',
    'manage_details': 'व्यक्तिगत विवरण प्रबंधित करें',
    'general': 'सामान्य',
    'about_app': 'ऐप के बारे में',
    'version_info': 'संस्करण जानकारी',
    'help_support': 'सहायता और समर्थन',
    'contact_us': 'मदद के लिए संपर्क करें',
    'logout': 'लॉग आउट',
    'logout_confirm': 'क्या आप लॉग आउट करना चाहते हैं?',
    'cancel': 'रद्द करें',
    'language': 'भाषा / Language',
    'select_language': 'भाषा चुनें',
    'english': 'English',
    'tamil': 'தமிழ் (Tamil)',
    'hindi': 'हिन्दी (Hindi)',
    'malayalam': 'മലയാളം (Malayalam)',
    'kannada': 'ಕನ್ನಡ (Kannada)',
  };

  static const Map<String, String> _malayalamStrings = {
    'app_name': 'അർബൻ സെർവ്',
    'welcome_guest': 'സ്വാഗതം',
    'hey': 'ഹലോ, ',
    'search_hint': 'സേവനങ്ങൾ, പ്ലംബിംഗ്, ക്ലീനിംഗ് തിരയുക...',
    'detecting_location': 'ലൊക്കേഷൻ കണ്ടെത്തുന്നു...',
    'gold_flash_sale': 'ഫ്ലാഷ് സെയിൽ',
    'gold_price_sub': '₹1 നു 3 മാസം',
    'renew_gold': 'ഗോൾഡ് മെമ്പർഷിപ്പ് പുതുക്കുക',
    'explore': 'കണ്ടെത്തുക',
    'offers': 'ഓഫറുകൾ',
    'cat_all': 'എല്ലാം',
    'cat_cleaning': 'ക്ലീനിംഗ്',
    'cat_plumbing': 'പ്ലംബിംഗ്',
    'cat_electrical': 'ഇലക്ട്രിക്കൽ',
    'cat_ac_service': 'എസി സർവീസ്',
    'cat_painting': 'പെയ്ന്റിംഗ്',
    'cat_carpentry': 'മരപ്പണി',
    'cat_pest_control': 'പെസ്റ്റ് കൺട്രോൾ',
    'filters': 'ഫിൽട്ടറുകൾ',
    'near_fast': 'അടുത്തുള്ളവ',
    'top_rated': 'മികച്ച റേറ്റിംഗ്',
    'price_low': 'വില ↑',
    'book_service': 'സർവീസ് ബുക്ക് ചെയ്യുക',
    'service_address': 'വിലാസം',
    'address_hint': 'പൂർണ്ണ വിലാസം നൽകുക',
    'address_required': 'വിലാസം ആവശ്യമാണ്',
    'preferred_date_time': 'തിയതിയും സമയവും',
    'tap_to_select': 'തിരഞ്ഞെടുക്കാൻ ടാപ്പ് ചെയ്യുക',
    'notes_optional': 'കുറിപ്പുകൾ',
    'notes_hint': 'പ്രത്യേക നിർദ്ദേശങ്ങൾ...',
    'confirm_booking': 'ബുക്കിംഗ് ഉറപ്പാക്കുക',
    'booking_placed': 'ബുക്കിംഗ് വിജയകരമായി പൂർത്തിയായി!',
    'booking_failed': 'ബുക്കിംഗ് പരാജയപ്പെട്ടു',
    'selected_pro': 'തിരഞ്ഞെടുത്ത പ്രൊഫഷണൽ',
    'my_bookings': 'എന്റെ ബുക്കിംഗുകൾ',
    'guest_mode': 'ഗസ്റ്റ് മോഡ്',
    'login_prompt': 'ബുക്കിംഗുകൾ കാണാൻ ലോഗിൻ ചെയ്യുക.',
    'login_register': 'ലോഗിൻ / രജിസ്റ്റർ ചെയ്യുക',
    'cancel_booking_title': 'ബുക്കിംഗ് ക്യാൻസൽ ചെയ്യുക',
    'cancel_booking_confirm': 'ക്യാൻസൽ ചെയ്യാൻ ആഗ്രഹിക്കുന്നുവോ?',
    'no': 'ഇല്ല',
    'yes_cancel': 'അതെ, ക്യാൻസൽ ചെയ്യുക',
    'booking_cancelled': 'ബുക്കിംഗ് ക്യാൻസൽ ചെയ്തു',
    'failed_to_cancel': 'ക്യാൻസൽ ചെയ്യാൻ പറ്റിയില്ല',
    'rebook': 'വീണ്ടും ബുക്ക് ചെയ്യുക',
    'status_pending': 'പെൻഡിംഗ്',
    'status_confirmed': 'കൺഫേം ചെയ്തു',
    'status_completed': 'പൂർത്തിയായി',
    'status_cancelled': 'ക്യാൻസൽ ചെയ്തു',
    'status_in_progress': 'നടന്നുകൊണ്ടിരിക്കുന്നു',
    'menu': 'മെനു',
    'guest_user': 'ഗസ്റ്റ് യൂസർ',
    'sign_in_access': 'ലോഗിൻ ചെയ്യുക',
    'account_settings': 'അക്കൗണ്ട് ക്രമീകരണങ്ങൾ',
    'edit_profile': 'പ്രൊഫൈൽ മാറ്റുക',
    'manage_details': 'വിവരങ്ങൾ നൽകുക',
    'general': 'ജനറൽ',
    'about_app': 'ആപ്പിനെക്കുറിച്ച്',
    'version_info': 'വേർഷൻ വിവരങ്ങൾ',
    'help_support': 'സഹായവും പിന്തുണയും',
    'contact_us': 'ബന്ധപ്പെടുക',
    'logout': 'ലോഗ് ഔട്ട്',
    'logout_confirm': 'ലോഗ് ഔട്ട് ചെയ്യണമെന്നുറപ്പാണോ?',
    'cancel': 'ക്യാൻസൽ',
    'language': 'ഭാഷ / Language',
    'select_language': 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    'english': 'English',
    'tamil': 'தமிழ் (Tamil)',
    'hindi': 'हिन्दी (Hindi)',
    'malayalam': 'മലയാളം (Malayalam)',
    'kannada': 'ಕನ್ನಡ (Kannada)',
  };

  static const Map<String, String> _kannadaStrings = {
    'app_name': 'ಅರ್ಬನ್ ಸರ್ವ್',
    'welcome_guest': 'ಸ್ವಾಗತ ಅತಿಥಿ',
    'hey': 'ಹಲೋ, ',
    'search_hint': 'ಸೇವೆಗಳು, ಪ್ಲಂಬಿಂಗ್, ಕ್ಲೀನಿಂಗ್ ಹುಡುಕಿ...',
    'detecting_location': 'ಸ್ಥಳ ಪತ್ತೆ ಮಾಡಲಾಗುತ್ತಿದೆ...',
    'gold_flash_sale': 'ಫ್ಲ್ಯಾಶ್ ಸೇಲ್',
    'gold_price_sub': '₹1 ಕ್ಕೆ 3 ತಿಂಗಳು',
    'renew_gold': 'ಗೋಲ್ಡ್ ಸದಸ್ಯತ್ವ ನವೀಕರಿಸಿ',
    'explore': 'ಅನ್ವೇಷಿಸಿ',
    'offers': 'ಆಫರ್‌ಗಳು',
    'cat_all': 'ಎಲ್ಲವೂ',
    'cat_cleaning': 'ಕ್ಲೀನಿಂಗ್',
    'cat_plumbing': 'ಪ್ಲಂಬಿಂಗ್',
    'cat_electrical': 'ಎಲೆಕ್ಟ್ರಿಕಲ್',
    'cat_ac_service': 'ಎಸಿ ಸೇವೆ',
    'cat_painting': 'ಪೇಂಟಿಂಗ್',
    'cat_carpentry': 'ಮರಗೆಲಸ',
    'cat_pest_control': 'ಕೀಟ ನಿಯಂತ್ರಣ',
    'filters': 'ಫಿಲ್ಟರ್‌ಗಳು',
    'near_fast': 'ಹತ್ತಿರ ಮತ್ತು ವೇಗ',
    'top_rated': 'ಉನ್ನತ ಶ್ರೇಣಿಯ',
    'price_low': 'ಬೆಲೆ ↑',
    'book_service': 'ಸೇವೆ ಬುಕ್ ಮಾಡಿ',
    'service_address': 'ಸೇವೆಯ ವಿಳಾಸ',
    'address_hint': 'ಪೂರ್ಣ ವಿಳಾಸ ನಮೂದಿಸಿ',
    'address_required': 'ವಿಳಾಸ ಅಗತ್ಯವಿದೆ',
    'preferred_date_time': 'ಆದ್ಯತೆಯ ದಿನಾಂಕ ಮತ್ತು ಸಮಯ',
    'tap_to_select': 'ಆಯ್ಕೆ ಮಾಡಲು ಟ್ಯಾಪ್ ಮಾಡಿ',
    'notes_optional': 'ಟಿಪ್ಪಣಿಗಳು',
    'notes_hint': 'ವಿಶೇಷ ಸೂಚನೆಗಳು...',
    'confirm_booking': 'ಬುಕಿಂಗ್ ಖಚಿತಪಡಿಸಿ',
    'booking_placed': 'ಬುಕಿಂಗ್ ಯಶಸ್ವಿಯಾಗಿದೆ!',
    'booking_failed': 'ಬುಕಿಂಗ್ ವಿಫಲವಾಗಿದೆ',
    'selected_pro': 'ಆಯ್ಕೆಯಾದ ತಜ್ಞರು',
    'my_bookings': 'ನನ್ನ ಬುಕಿಂಗ್‌ಗಳು',
    'guest_mode': 'ಅತಿಥಿ ಮೋಡ್ ಸಕ್ರಿಯವಾಗಿದೆ',
    'login_prompt': 'ಬುಕಿಂಗ್ ನೋಡಲು ಲಾಗಿನ್ ಮಾಡಿ.',
    'login_register': 'ಲಾಗಿನ್ / ನೋಂದಾಯಿಸಿ',
    'cancel_booking_title': 'ಬುಕಿಂಗ್ ರದ್ದುಗೊಳಿಸಿ',
    'cancel_booking_confirm': 'ರದ್ದುಗೊಳಿಸಲು ನೀವು ಖಚಿತವಾಗಿದ್ದೀರಾ?',
    'no': 'ಇಲ್ಲ',
    'yes_cancel': 'ಹೌದು, ರದ್ದುಗೊಳಿಸಿ',
    'booking_cancelled': 'ಬುಕಿಂಗ್ ರದ್ದುಗೊಳಿಸಲಾಗಿದೆ',
    'failed_to_cancel': 'ರದ್ದುಗೊಳಿಸಲು ವಿಫಲವಾಗಿದೆ',
    'rebook': 'ಮತ್ತೆ ಬುಕ್ ಮಾಡಿ',
    'status_pending': 'ಬಕಿ ಇದೆ',
    'status_confirmed': 'ಖಚಿತಪಡಿಸಲಾಗಿದೆ',
    'status_completed': 'ಪೂರ್ಣಗೊಂಡಿದೆ',
    'status_cancelled': 'ರದ್ದುಗೊಳಿಸಲಾಗಿದೆ',
    'status_in_progress': 'ಪ್ರಗತಿಯಲ್ಲಿದೆ',
    'menu': 'ಮೆನು',
    'guest_user': 'ಅತಿಥಿ ಬಳಕೆದಾರ',
    'sign_in_access': 'ಲಾಗಿನ್ ಮಾಡಿ',
    'account_settings': 'ಖಾತೆ ಸಂಯೋಜನೆಗಳು',
    'edit_profile': 'ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ',
    'manage_details': 'ವಿವರಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
    'general': 'ಸಾಮಾನ್ಯ',
    'about_app': 'ಆಪ್ ಬಗ್ಗೆ',
    'version_info': 'ಆವೃತ್ತಿ ಮಾಹಿತಿ',
    'help_support': 'ಸಹಾಯ ಮತ್ತು ಬೆಂಬಲ',
    'contact_us': 'ಸಂಪರ್ಕಿಸಿ',
    'logout': 'ಲಾಗ್ ಔಟ್',
    'logout_confirm': 'ಲಾಗ್ ಔಟ್ ಮಾಡಲು ಬಯಸುವಿರಾ?',
    'cancel': 'ರದ್ದುಗೊಳಿಸಿ',
    'language': 'ಭಾಷೆ / Language',
    'select_language': 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    'english': 'English',
    'tamil': 'தமிழ் (Tamil)',
    'hindi': 'हिन्दी (Hindi)',
    'malayalam': 'മലയാളം (Malayalam)',
    'kannada': 'ಕನ್ನಡ (Kannada)',
  };
}

extension TranslationExtension on BuildContext {
  String translate(String key) {
    try {
      return Provider.of<LanguageProvider>(this).translate(key);
    } catch (_) {
      return key;
    }
  }
}
